#VERSION:1.2
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: webhook-springcloud
  namespace: springcloud
  labels:
    app: webhook-springcloud
spec:
  serviceName: webhook-springcloud
  selector:
    matchLabels:
      app: webhook-springcloud
  replicas: 2
  template:
    metadata:
      name: webhook-springcloud
      labels:
        app: webhook-springcloud
    spec:
      serviceAccountName: sa-springcloud
      containers:
      - name: webhook-springcloud
        image: harbor.io/springcloud/webhook-springcloud:0.0.1
        imagePullPolicy: Always
        env:
        - name: SERVER_PORT
          value: "9999" 
        - name: PROFILE
          value: prod
        envFrom:
        - configMapRef:
            name: "webhook-springcloud-cm"        
        - secretRef:
            name: "webhook-springcloud-secret"           
        ports:
        - name: containerport
          containerPort: 9999
        resources:
          requests:
            cpu: 128m
            memory: 128Mi
          limits:
            cpu: 1024m
            memory: 1024Mi
---
apiVersion: v1
kind: Service
metadata:
  name: webhook-springcloud
  namespace: springcloud  
spec:
  type: ClusterIP
  selector:
    app: webhook-springcloud
  ports:
  - name: port1
    port: 9999
    targetPort: 9999
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: webhook-springcloud
  namespace: springcloud  
spec:
  rules:
  - host: {{ SERVICE_HOST }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: webhook-springcloud 
            port: 
              number: 9999
